repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: .venv/Scripts/python.exe -m mypy
        types: [python]
        exclude: ^tests
        require_serial: true
  - repo: https://github.com/pdm-project/pdm
    rev: 2.11.1
    hooks:
      - id: pdm-lock-check
      - id: pdm-export
        args: ["-G", ":all", "--pyproject", "-o", "requirements.txt"]
        files: ^pdm.lock$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
