version: "3"

services:
  test-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: casbin_rule

  test:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.7"
    volumes:
      - .:/casbin-tortoise
    depends_on:
      - test-db
