version: "3"

services:
  test-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "casbin_rule"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build: .
    volumes:
      - .:/casbin-tortoise
    depends_on:
      test-db:
        condition: service_healthy
