services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "casbin_rule"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

  test:
    build: .
    volumes:
      - .:/casbin-tortoise
    depends_on:
      postgres:
        condition: service_healthy
