name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - run: python3 -m pip install mypy
      - name: Check typing
        run: mypy --pretty .
      - name: Check formatting
        uses: chartboost/ruff-action@v1
        with:
          args: check --target-version=py37

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
        experimental: [false]
        include:
          - python-version: "3.12"
            experimental: true

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "casbin_rule"
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
        env:
          POSTGRES_HOST: "localhost"
